### ISSUE TITLE
Does it support deflate compression?

### ISSUE THREAD

**Issue by Klesh-** [scalecube/socketio#46]
I want to write a game server, and I need to reduce the traffic between the client and the server, is there any compression support?

**Comment by antonkharenko** [comment]
No, there is no build in compression support, but when you send message to client and receive it you are working with ByteBuf, like:
```
  public void onMessage(Session session, ByteBuf message) {
    System.out.println("Received: " + message.toString(CharsetUtil.UTF_8));
    message.release();
  }
```
In typical use case you will use JSON in UTF-8 encoding. One thing that comes to my mind directly is instead of putting plain JSON you can compress it with [msgpack ](http://msgpack.org/index.html). Or basically use some other compression mechanism - on server side you may work directly with bytes, on client it will be either Websocket or HTTP so result should be some compressed string, and you need to decompress it on client side once received.

**Comment by antonkharenko** [comment]
Regards deflate compression basically I think you can do it, but probably you will need additional binary-to-string (e.g. base64) encoding/decoding on top of binary compression

**Comment by Klesh-** [comment]
Thanks for the answer! 
I implemented data compression, using GZIP on the server side and pako.js on the client side. This reduced the traffic from 4MiB / s to 600KiB / s!

**Comment by antonkharenko** [comment]
Great, good results and thanks for info!  Is it work well even without any binary-to-string conversion (base64 or so) on both transports websocket and http (in case of fallback to xhr-polling)?

**Comment by Klesh-** [comment]
Yes, I had to do base64 conversion on both sides.
I also looked how the built-in compression works in this library: [https://github.com/mrniko/netty-socketio](url) and also did:
```
...
public static final String HTTP_COMPRESSION = "httpCompression";
public static final String WEB_SOCKET_TRANSPORT_COMPRESSION = "webSocketTransportCompression";
...
private SocketIOServer socketIOServer;
...
this.socketIOServer = SocketIOServer.newInstance(...);
this.socketIOServer.setPipelineModifier(pipeline -> {
    pipeline.addAfter (SocketIOChannelInitializer.HTTP_RESPONSE_ENCODER, HTTP_COMPRESSION, new HttpContentCompressor());
    pipeline.addBefore (SocketIOChannelInitializer.SOCKETIO_HEARTBEAT_HANDLER, WEB_SOCKET_TRANSPORT_COMPRESSION, new WebSocketServerCompressionHandler());
});
```
From: [https://github.com/mrniko/netty-socketio/blob/master/src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java](url)    

It turned out much easier and without using third-party libraries and base64 conversion. 
Maybe add it as a feature for the built-in compression?

**Comment by antonkharenko** [comment]
yeah, make sense!

**Comment by antonkharenko** [comment]
Created PR for compression support: https://github.com/scalecube/socketio/pull/47

I will make new release shortly after merging this PR, since your pipeline modifier solution won't really work for websockets since previously handshaker was created as `new WebSocketServerHandshakerFactory(location, null, false, frameSize)`, where `false` means do not allow extensions.

**Comment by antonkharenko** [comment]
Done at version 2.3.4

**Comment by Klesh-** [comment]
Thanks very much!
