### ISSUE TITLE
How to get Header

### ISSUE THREAD

**Issue by BadDeveloper2022** [scalecube/socketio#48]
How to get Header

**Comment by antonkharenko** [comment]
In basic pipeline we do not pass headers out of Session interfaces due to differences in actual underlying protocols: websocket - handshake http request, upgrade protocol and websocket frame fruthers; xhr-polling - handshake, polling get requests and post requests to send message etc.  

But it is possible to customize pipeline using [PipelineModifier](https://github.com/scalecube/socketio/blob/master/src/main/java/io/scalecube/socketio/PipelineModifier.java) which you set with `SocketIOServer.setPipelineModifier(..)`. So you may add some custom Netty handlers to the pipeline with additional logic like storing headers.

**Comment by BadDeveloper2022** [comment]
thank you
